changelog:
  exclude:
    authors:
      - renovate[bot]
      - dependabot[bot]
  categories:
    - title: Features
      labels:
        - features
    - title: Dependencies
      labels:
        - dependencies
    - title: Bug Fixes
      labels:
        - fixes
    - title: Other Changes
      labels:
        - "*"
      exclude:
        labels:
          - features
          - dependencies
          - fixes